version: "3.6"

services:
  app:
    image: ${IMAGE_APP}
    ports:
      - ${APP_PORT}:80
    volumes:
      - .env:/var/www/html/.env
    environment:
      SKIP_COMPOSER: 1
      SKIP_CHOWN: 1
    links:
      - database

  database:
    image: ${IMAGE_DATABASE}
    restart: always
    ports:
      - 5432:5432
    volumes:
      - eva-auth-db:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    image: ${IMAGE_REDIS}

volumes:
  eva-auth-db:
